# Generated by OmopViewer 0.4.0
# Be careful editing this file

server <- function(input, output, session) {
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(fileName = file)
    }
  )
  
  # summarise_omop_snapshot -----
  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotTable <- shiny::reactive({
    data[["summarise_omop_snapshot"]]  |>
      OmopSketch::tableOmopSnapshot()
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )
  # summarise_cohort_count -----
  ## get summarise_cohort_count data
  getSummariseCohortCountData <- shiny::reactive({
    data[["summarise_cohort_count"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_count_cdm_name,
        .data$group_level %in% input$summarise_cohort_count_cohort_name,
        .data$variable_name %in% input$summarise_cohort_count_variable_name
      ) |>
      omopgenerics::filterSettings(.data$table_name %in% input$summarise_cohort_count_table_name)
  })
  getSummariseCohortCountTidy <- shiny::reactive({
    tidyDT(getSummariseCohortCountData(), input$summarise_cohort_count_tidy_columns, input$summarise_cohort_count_tidy_pivot_estimates)
  })
  output$summarise_cohort_count_tidy <- DT::renderDT({
    getSummariseCohortCountTidy()
  })
  output$summarise_cohort_count_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseCohortCountData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseCohortCountTable <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::tableCohortCount(
        header = input$summarise_cohort_count_table_header,
        groupColumn = input$summarise_cohort_count_table_group_column,
        hide = input$summarise_cohort_count_table_hide
      )
  })
  output$summarise_cohort_count_table <- gt::render_gt({
    getSummariseCohortCountTable()
  })
  output$summarise_cohort_count_table_download <- shiny::downloadHandler(
    filename = paste0("table_count.", input$summarise_cohort_count_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortCountTable(), file)
    }
  )
  getSummariseCohortCountPlot <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::plotCohortCount(
        facet = input$summarise_cohort_count_plot_facet,
        colour = input$summarise_cohort_count_plot_colour
      )
  })
  output$summarise_cohort_count_plot <- shiny::renderUI({
    x <- getSummariseCohortCountPlot()
    renderInteractivePlot(x, input$summarise_cohort_count_plot_interactive)
  })
  output$summarise_cohort_count_plot_download <- shiny::downloadHandler(
    filename = "plot_count.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCohortCountPlot(),
        width = as.numeric(input$summarise_cohort_count_plot_width),
        height = as.numeric(input$summarise_cohort_count_plot_height),
        units = input$summarise_cohort_count_plot_units,
        dpi = as.numeric(input$summarise_cohort_count_plot_dpi)
      )
    }
  )
  # summarise_cohort_attrition -----
  ## get summarise_cohort_attrition data
  getSummariseCohortAttritionData <- shiny::reactive({
    data[["summarise_cohort_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_attrition_cdm_name,
        .data$group_level %in% input$summarise_cohort_attrition_cohort_name,
        .data$variable_name %in% input$summarise_cohort_attrition_variable_name
      )
  })
  getSummariseCohortAttritionTidy <- shiny::reactive({
    tidyDT(getSummariseCohortAttritionData(), input$summarise_cohort_attrition_tidy_columns, input$summarise_cohort_attrition_tidy_pivot_estimates)
  })
  output$summarise_cohort_attrition_tidy <- DT::renderDT({
    getSummariseCohortAttritionTidy()
  })
  output$summarise_cohort_attrition_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseCohortAttritionData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseCohortAttritionTable <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::tableCohortAttrition(
        header = input$summarise_cohort_attrition_table_header,
        groupColumn = input$summarise_cohort_attrition_table_group_column,
        hide = input$summarise_cohort_attrition_table_hide
      )
  })
  output$summarise_cohort_attrition_table <- gt::render_gt({
    getSummariseCohortAttritionTable()
  })
  output$summarise_cohort_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_attrition.", input$summarise_cohort_attrition_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortAttritionTable(), file)
    }
  )
  getSummariseCohortAttritionDiagram <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::plotCohortAttrition(
        show = input$summarise_cohort_attrition_diagram_show
      )
  })
  output$summarise_cohort_attrition_diagram <- DiagrammeR::renderGrViz({
    getSummariseCohortAttritionDiagram()
  })
  output$summarise_cohort_attrition_diagram_download <- shiny::downloadHandler(
    filename = "attrition_diagram.png",
    content = function(file) {
      svg <- DiagrammeRsvg::export_svg(getSummariseCohortAttritionDiagram())
      rsvg::rsvg_png(charToRaw(svg), file, width = input$summarise_cohort_attrition_diagram_width)
    }
  )
  # cohort_code_use -----
  filterCohortCodeUse <- shiny::reactive({
    result <- data$cohort_code_use |>
      visOmopResults::splitGroup(keep = TRUE) |>
      visOmopResults::splitAdditional(keep = TRUE) |>
      dplyr::filter(.data$cdm_name %in% input$cohort_code_use_cdm_name,
                    .data$cohort_name %in% input$cohort_code_use_cohort_name,
                    .data$domain_id %in% input$cohort_code_use_domain_id) |>
      dplyr::select(-visOmopResults::groupColumns(data$cohort_code_use)) |>
      dplyr::select(-visOmopResults::additionalColumns(data$cohort_code_use))
    
    if(isFALSE(input$cohort_code_use_person_count)){
      result <- result  |>
        filter(estimate_name != "person_count")
    }
    if(isFALSE(input$cohort_code_use_record_count)){
      result <- result  |>
        filter(estimate_name != "record_count")
    }
    return(result)
  })
  ## Table cohort_code_use -----
  createCohortCodeUseGT <- shiny::reactive({
    tbl <- CodelistGenerator::tableCohortCodeUse(
      filterCohortCodeUse(),
      header = input$cohort_code_use_gt_header,
      groupColumn = input$cohort_code_use_gt_groupColumn,
      hide = input$cohort_code_use_gt_hide
    ) %>%
      tab_header(
        title = "Summary of cohort code use",
        subtitle = "Codes from codelist observed on day of cohort entry. Note more than one code could be seen for a person on this day (both of which would have led to inclusion)."
      ) %>%
      tab_options(
        heading.align = "left"
      )
    
    return(tbl)
  })
  createCohortCodeUseInteractive <- shiny::reactive({
    tbl <-  CodelistGenerator::tableCohortCodeUse(
      filterCohortCodeUse(),
      header = input$cohort_code_use_gt_header,
      groupColumn = input$cohort_code_use_gt_groupColumn,
      hide = input$cohort_code_use_gt_hide,
      type = "tibble"
    )
    names(tbl) <-stringr::str_remove_all(names(tbl),
                                         "\\[header_name\\]Database name\\n\\[header_level\\]")
    names(tbl) <- stringr::str_remove_all(names(tbl),
                                          "Estimate name\n\\[header_level\\]")
    names(tbl) <- stringr::str_replace_all(names(tbl),
                                           "\n\\[header_name\\]",
                                           ": ")
    return(tbl)
  })
  output$cohort_code_use_tbl <- shiny::renderUI({
    
    if(isFALSE(input$cohort_code_use_interactive)){
      tbl <- createCohortCodeUseGT()
      return(tbl)
    } else {
      tbl <- createCohortCodeUseInteractive() |>
        dplyr::mutate(dplyr::across(c(ends_with("count")),
                                    ~ gsub(",", "", .))) |>
        dplyr::mutate(dplyr::across(c(ends_with("count")),
                                    ~ suppressWarnings(as.numeric(.))))
      
      # column ordering by codelist and first column with a count
      order <- list("Cohort name"  = "asc",
                    "count" = "desc")
      names(order)[2] <- names(tbl)[9]
      
      # suppressed to NA
      tbl <- tbl |>
        purrr::map_df(~ ifelse(grepl("^<", .), NA, .))
      
      tbl <- reactable(tbl,
                       columns = getColsForTbl(tbl,
                                               sortNALast = FALSE,
                                               names = c("Standard concept ID", "Source concept ID")),
                       defaultSorted = order,
                       filterable = TRUE,
                       searchable = TRUE,
                       defaultPageSize = 25,
                       highlight = TRUE,
                       striped = TRUE,
                       compact = TRUE,
                       showSortable = TRUE) |>
        reactablefmtr::add_title("Summary of cohort code use",
                                 font_size = 25,
                                 font_weight = "normal") |>
        reactablefmtr::add_subtitle("Codes from codelist observed on day of cohort entry. Note more than one code could be seen for a person on this day (both of which would have led to inclusion).",
                                    font_size = 15,
                                    font_weight = "normal")
      
      return(tbl)
    }
  })
  
  output$cohort_code_use_download <- shiny::downloadHandler(
    filename = function(){
      if(isFALSE(input$cohort_code_use_interactive)){
        file <- "summarise_cohort_code_use_gt.docx"
      }else{
        file <- "summarise_cohort_code_use_tbl.csv"
      }
      return(file)
    },
    content = function(file){
      if(isFALSE(input$cohort_code_use_interactive)){
        gt::gtsave(data = createCohortCodeUseGT(), filename = file)
      }else{
        readr::write_csv(createCohortCodeUseInteractive(), file = file)
      }
    }
  )
  # summarise_characteristics -----
  ## get summarise_characteristics data
  getSummariseCharacteristicsData <- shiny::reactive({
    x1 <- input$summarise_characteristics_cohort_name
    x2 <- input$summarise_characteristics_cohort_name_type
    cohortName <- do.call(paste0, expand.grid(x1, paste0("_", x2)))
    cohortName <- gsub("_original", "", cohortName)
    data[["summarise_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_characteristics_cdm_name,
        .data$variable_name %in% input$summarise_characteristics_variable_name,
        .data$estimate_name %in% input$summarise_characteristics_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% cohortName) |>
      omopgenerics::filterStrata(
        .data$maternal_age_group %in% input$summarise_characteristics_maternal_age_group,
        .data$pregnancy_start_period %in% input$summarise_characteristics_pregnancy_start_period,
        .data$ethnicity %in% input$summarise_characteristics_ethnicity,
        .data$socioeconomic_status %in% input$summarise_characteristics_socioeconomic_status,
        .data$trimester %in% input$summarise_characteristics_trimester,
        .data$nationallity %in% input$summarise_characteristics_nationallity,
        .data$birth_continent %in% input$summarise_characteristics_birth_continent
      )
  })
  getSummariseCharacteristicsTable <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      dplyr::filter(
        !variable_name %in% c("Cohort start date", "Cohort end date", "Age", "Sex", "Prior observation", "Future observation", "Days in cohort")
      ) |>
      dplyr::mutate(
        estimate_value = if_else(variable_name == "Previous pregnancies" & .data$estimate_name != "sd", as.character(as.numeric(.data$estimate_value) - 1), .data$estimate_value),
        variable_level = dplyr::if_else(variable_name == "Previous pregnancies", "-", variable_level),
        variable_name = factor(
          variable_name,
          levels = c(
            "Number records", "Number subjects", "Maternal age", "Maternal age group",
            "Trimester", "Season", "Previous pregnancies",
            "Ethnicity", "Birth continent", "Nationallity", 
            'Socioeconomic status',
            "Mental heatlh problems in the last year",
            "Covariates in the past 5 years",
            "History of comorbidities", "Medications in the past year"
          ),
          labels = c(
            "Number pregnancies", "Number subjects", "Maternal age", "Maternal age group",
            "Trimester", "Season", "Previous pregnancies",
            "Ethnicity", "Birth continent", "Nationallity",
            'Socioeconomic status',
            "Mental heatlh problems in the last year",
            "Covariates in the past 5 years",
            "History of comorbidities", "Medications in the past year"
          )
        ),
        strata_level = factor(
          strata_level,
          levels = c(
            "overall", "12 to 17", "18 to 34", "35 to 55", "Pre COVID-19",
            "COVID-19 main outbreak", "Post COVID-19 main outbreak",
            paste0(1:10), "White", "Black", "Asian", "Missing",
            paste0("Trimester ", 1:3), "Postpartum"
          )
        )
      ) |>
      dplyr::filter(!is.na(variable_name)) |>
      dplyr::arrange(variable_name, variable_level, strata_level) |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_characteristics_table_header,
        groupColumn = input$summarise_characteristics_table_group_column,
        hide = input$summarise_characteristics_table_hide
      )
  })
  output$summarise_characteristics_table <- gt::render_gt({
    getSummariseCharacteristicsTable()
  })
  output$summarise_characteristics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_characteristics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCharacteristicsTable(), file)
    }
  )
  getSummariseCharacteristicsPlot <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_characteristics_plot_plot_type,
        facet = input$summarise_characteristics_plot_facet,
        colour = input$summarise_characteristics_plot_colour
      )
  })
  output$summarise_characteristics_plot <- shiny::renderUI({
    x <- getSummariseCharacteristicsPlot()
    renderInteractivePlot(x, input$summarise_characteristics_plot_interactive)
  })
  output$summarise_characteristics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCharacteristicsPlot(),
        width = as.numeric(input$summarise_characteristics_plot_width),
        height = as.numeric(input$summarise_characteristics_plot_height),
        units = input$summarise_characteristics_plot_units,
        dpi = as.numeric(input$summarise_characteristics_plot_dpi)
      )
    }
  )
  # summarise_large_scale_characteristics -----
  ## get summarise_large_scale_characteristics data
  getSummariseLargeScaleCharacteristicsData <- shiny::reactive({
    x1 <- input$summarise_large_scale_characteristics_cohort_name
    x2 <- input$summarise_large_scale_characteristics_cohort_name_type
    cohortName <- do.call(paste0, expand.grid(x1, paste0("_", x2)))
    cohortName <- gsub("_original", "", cohortName)
    data[["summarise_large_scale_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_large_scale_characteristics_cdm_name,
        .data$variable_level %in% input$summarise_large_scale_characteristics_variable_level
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% cohortName) |>
      omopgenerics::filterSettings(
        .data$table_name %in% input$summarise_large_scale_characteristics_table_name,
        .data$type %in% input$summarise_large_scale_characteristics_type
      ) |>
      omopgenerics::filterStrata(
        .data$maternal_age_group %in% input$summarise_large_scale_characteristics_maternal_age_group,
        .data$pregnancy_start_period %in% input$summarise_large_scale_characteristics_pregnancy_start_period,
        .data$ethnicity %in% input$summarise_large_scale_characteristics_ethnicity,
        .data$nationallity %in% input$summarise_large_scale_characteristics_nationallity,
        .data$birth_continent %in% input$summarise_large_scale_characteristics_birth_continent,
        .data$socioeconomic_status %in% input$summarise_large_scale_characteristics_socioeconomic_status,
        .data$trimester %in% input$summarise_large_scale_characteristics_trimester
      )
  })
  getSummariseLargeScaleCharacteristicsTableLsc <- shiny::reactive({
    dropCols <- input$summarise_large_scale_characteristics_table_lsc_hide
    dropCols[dropCols == "variable_name"] <- "concept_name"
    getSummariseLargeScaleCharacteristicsData() |>
      # omopgenerics::newSummarisedResult(settings = omopgenerics::settings(res) |> dplyr::mutate(additional = "concept_id")) |>
      omopgenerics::tidy() |>
      dplyr::rename("concept_name" = "variable_name") |>
      dplyr::relocate(c("count", "percentage"), .after = dplyr::last_col()) |>
      dplyr::select(!dplyr::any_of(c("analysis", "type", dropCols))) |>
      visOmopResults::formatTable(type = "reactable")
  })
  output$summarise_large_scale_characteristics_table_lsc <- reactable::renderReactable({
    getSummariseLargeScaleCharacteristicsTableLsc()
  })
  output$summarise_large_scale_characteristics_table_lsc_download <- shiny::downloadHandler(
    filename = "lsc_results.csv",
    content = function(file) {
      rt <- getSummariseLargeScaleCharacteristicsTableLsc()
      rt$x$tag$attribs$data |>
        unclass() |>
        jsonlite::fromJSON() |>
        dplyr::as_tibble() |>
        readr::write_csv(file)
    }
  )
  getSummariseLargeScaleCharacteristicsComparedData <- shiny::reactive({
    x1 <- input$summarise_large_scale_characteristics_cohort_name
    x2 <- input$summarise_large_scale_characteristics_cohort_name_type
    cohortName1 <- do.call(paste0, expand.grid(x1, paste0("_", x2)))
    cohortName1 <- gsub("_original", "", cohortName1)
    y1 <- input$summarise_large_scale_characteristics_compared_cohort_name
    y2 <- input$summarise_large_scale_characteristics_compared_cohort_name_type
    cohortName2 <- do.call(paste0, expand.grid(y1, paste0("_", y2)))
    cohortName2 <- gsub("_original", "", cohortName2)
    data[["summarise_large_scale_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_large_scale_characteristics_cdm_name,
        .data$variable_level %in% input$summarise_large_scale_characteristics_variable_level
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% c(cohortName1, cohortName2)) |>
      omopgenerics::filterSettings(
        .data$table_name %in% input$summarise_large_scale_characteristics_table_name,
        .data$type %in% input$summarise_large_scale_characteristics_type
      ) |>
      omopgenerics::filterStrata(
        .data$maternal_age_group %in% input$summarise_large_scale_characteristics_maternal_age_group,
        .data$pregnancy_start_period %in% input$summarise_large_scale_characteristics_pregnancy_start_period,
        .data$ethnicity %in% input$summarise_large_scale_characteristics_ethnicity,
        .data$nationallity %in% input$summarise_large_scale_characteristics_nationallity,
        .data$birth_continent %in% input$summarise_large_scale_characteristics_birth_continent,
        .data$socioeconomic_status %in% input$summarise_large_scale_characteristics_socioeconomic_status,
        .data$trimester %in% input$summarise_large_scale_characteristics_trimester
      ) |>
      dplyr::filter(estimate_name == "percentage") |>
      omopgenerics::tidy() |>
      tidyr::pivot_wider(names_from = "cohort_name", values_from = "percentage") |>
      dplyr::mutate(
        SMD = if_else(
          .data[[cohortName2]] == .data[[cohortName1]], 0,
          (.data[[cohortName2]]/100 - .data[[cohortName1]]/100) / sqrt((.data[[cohortName1]]/100*(1-.data[[cohortName1]]/100) + .data[[cohortName2]]/100*(1-.data[[cohortName2]]/100))/2)
        ),
        ASMD = abs(SMD)
      ) |>
      dplyr::filter(!is.na(ASMD)) |>
      dplyr::rename("concept_name" = "variable_name")
  })
  getSummariseLargeScaleCharacteristicsComparedTableLsc <- shiny::reactive({
    x1 <- input$summarise_large_scale_characteristics_cohort_name
    x2 <- input$summarise_large_scale_characteristics_cohort_name_type
    cohortName1 <- do.call(paste0, expand.grid(x1, paste0("_", x2)))
    cohortName1 <- gsub("_original", "", cohortName1)
    y1 <- input$summarise_large_scale_characteristics_compared_cohort_name
    y2 <- input$summarise_large_scale_characteristics_compared_cohort_name_type
    cohortName2 <- do.call(paste0, expand.grid(y1, paste0("_", y2)))
    cohortName2 <- gsub("_original", "", cohortName2)
    dropCols <- input$summarise_large_scale_characteristics_table_lsc_compared_hide
    dropCols[dropCols == "variable_name"] <- "concept_name"
    getSummariseLargeScaleCharacteristicsComparedData() |>
      dplyr::select(!dplyr::any_of(c("analysis", dropCols))) |>
      dplyr::rename(!!paste0(cohortName1, " (%)") := cohortName1, !!paste0(cohortName2, " (%)") := cohortName2) |>
      visOmopResults::formatTable(type = "reactable")
  })
  output$summarise_large_scale_characteristics_table_lsc_compared <- reactable::renderReactable({
    getSummariseLargeScaleCharacteristicsComparedTableLsc() 
  })
  output$summarise_large_scale_characteristics_table_lsc_compared_download <- shiny::downloadHandler(
    filename = "smd_results.csv",
    content = function(file) {
      rt <- getSummariseLargeScaleCharacteristicsComparedTableLsc()
      rt$x$tag$attribs$data |>
        unclass() |>
        jsonlite::fromJSON() |>
        dplyr::as_tibble() |>
        readr::write_csv(file)
    }
  )
  getComparedLSCPlot <- shiny::reactive({
    x1 <- input$summarise_large_scale_characteristics_cohort_name
    x2 <- input$summarise_large_scale_characteristics_cohort_name_type
    cohortName1 <- do.call(paste0, expand.grid(x1, paste0("_", x2)))
    cohortName1 <- gsub("_original", "", cohortName1)
    y1 <- input$summarise_large_scale_characteristics_compared_cohort_name
    y2 <- input$summarise_large_scale_characteristics_compared_cohort_name_type
    cohortName2 <- do.call(paste0, expand.grid(y1, paste0("_", y2)))
    cohortName2 <- gsub("_original", "", cohortName2)
    p <- getSummariseLargeScaleCharacteristicsComparedData() |>
      visOmopResults::scatterPlot(
        x = cohortName1,
        y = cohortName2,
        line = FALSE,
        point = TRUE,
        ribbon = FALSE,
        ymin = NULL,
        ymax = NULL,
        facet = input$summarise_large_scale_characteristics_plot_compared_facet,
        colour = input$summarise_large_scale_characteristics_plot_compared_colour,
        label = c("ASMD", "SMD", "concept_name")
      ) +
      ggplot2::xlab(paste0(cohortName1, " (%)")) +
      ggplot2::ylab(paste0(cohortName2, " (%)")) +
      ggplot2::geom_abline(slope = 1, intercept = 0, linetype = "dashed", colour = "gray")
    if (!input$legend_none) {
      p <- p + ggplot2::theme(legend.position = "none")
    }
  })
  output$summarise_large_scale_characteristics_plot_compared <- shiny::renderUI({
    x <- getComparedLSCPlot()
    renderInteractivePlot(x, input$summarise_large_scale_characteristics_plot_interactive)
  })
  output$summarise_large_scale_characteristics_plot_download <- shiny::downloadHandler(
    filename = "plot_lsc.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getComparedLSCPlot(),
        width = as.numeric(input$summarise_large_scale_characteristics_plot_width),
        height = as.numeric(input$summarise_large_scale_characteristics_plot_height),
        units = input$summarise_large_scale_characteristics_plot_units,
        dpi = as.numeric(input$summarise_large_scale_characteristics_plot_dpi)
      )
    }
  )
  # incidence data  ----
  getIncidenceData <- shiny::reactive({
    data[["incidence"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$incidence_cdm_name,
        .data$estimate_name %in% input$incidence_estimate_name
      ) |>
      omopgenerics::filterGroup(
        .data$outcome_cohort_name %in% input$incidence_outcome_cohort_name
      ) |>
      omopgenerics::filterStrata(
        .data$maternal_age_group %in% input$incidence_maternal_age_group,
        .data$pregnancy_start_period %in% input$incidence_pregnancy_start_period,
        .data$ethnicity %in% input$incidence_ethnicity,
        .data$nationallity %in% input$incidence_nationallity,
        .data$birth_continent %in% input$incidence_birth_continent,
        .data$socioeconomic_status %in% input$incidence_socioeconomic_status,
        .data$gestational_trimester %in% input$incidence_gestational_trimester
      ) |>
      omopgenerics::filterAdditional(
        .data$outcome_group %in% input$incidence_outcome_group
      )
  })
  output$incidence_outcome_cohort_name_picker <- shiny::renderUI({
    opts <- data[["incidence"]]  |>
      omopgenerics::filterAdditional(
        .data$outcome_group %in% input$incidence_outcome_group
      ) |>
      dplyr::pull(group_level) |>
      unique()
    shinyWidgets::pickerInput(
      inputId = "incidence_outcome_cohort_name",
      label = "Outcome cohort name",
      choices = opts,
      selected = opts,
      multiple = TRUE,
      options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
    )
  })
  getIncidenceTidy <- shiny::reactive({
    getIncidenceData() |>
      omopgenerics::tidy() |>
      dplyr::mutate(
        outcome_group = factor(
          .data$outcome_group, 
          levels = c("Adverse Events of Special Interest", "Maternal Adverse Events", "AESI Sensitivity (180 wash-out)")
        ),
        maternal_age_group = factor(
          maternal_age_group, levels = c("overall", "12 to 17", "18 to 34", "35 to 55")
        ),
        pregnancy_start_period = factor(
          pregnancy_start_period, levels = c("overall", "Pre COVID-19", "COVID-19 main outbreak", "Post COVID-19 main outbreak")
        ),
        socioeconomic_status = factor(
          socioeconomic_status, c("overall", paste0("Q", 1:5), "R", paste0("U", 1:5), "0N", "Missing")
        ),
        ethnicity = factor(
          ethnicity, levels = c("overall", "White", "Black", "Asian", "Missing")
        ),
        nationallity = factor(
          nationallity, levels = c("overall", "Africa", "Asia", "Central/South America", "Europe", "North America", "Oceania", "Missing")
        ),
        birth_continent = factor(
          birth_continent, levels = c("overall", "Africa", "Asia", "Central/South America", "Europe", "North America", "Oceania", "Missing")
        )
      ) |>
      dplyr::filter(!is.na(.data$outcome_group)) |>
      dplyr::arrange(maternal_age_group, pregnancy_start_period, socioeconomic_status, ethnicity, nationallity, birth_continent, outcome_group) |>
      dplyr::select(dplyr::any_of(c(input$incidence_tidy_columns))) |>
      visOmopResults::formatTable(type = "reactable")
  })
  output$incidence_tidy <- reactable::renderReactable({
    getIncidenceTidy()
  })
  output$incidence_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getIncidenceData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getIncidenceTable <- shiny::reactive({
    res <- getIncidenceData() 
    outcomes <- res |>
      dplyr::filter(estimate_name == "incidence_100000_pys") |>
      dplyr::mutate(estimate_value = as.numeric(estimate_value)) |>
      dplyr::arrange(desc(estimate_value)) |>
      dplyr::pull(group_level) |>
      unique()
    res <- dplyr::bind_rows(
      res, 
      res |>
        omopgenerics::pivotEstimates() |>
        dplyr::mutate(estimate_value = if_else(!is.na(outcome_count), as.character(outcome_count/denominator_count * 100), NA_character_)) |>
        dplyr::mutate(
          estimate_name = "outcome_percentage",
          estimate_type = "percentage"
        )  |>
        dplyr::select(omopgenerics::resultColumns())
    )
    res |>
      visOmopResults::visOmopTable(
        estimateName = c(
          "Pregnancies" = "<denominator_count>",
          "Outcomes" = "<outcome_count> (<outcome_percentage> %)",
          "Outcomes in period" = "<outcome_in_period_count> (<outcome_in_period_percentage>%)",
          "Person-Days" = "<person_days_count>",
          "Person-Years" = "<person_years>",
          "Incidence" = c("<incidence_100000_pys> (<incidence_100000_pys_95CI_lower> - <incidence_100000_pys_95CI_upper>)")
        ),
        header = input$incidence_table_header,
        groupColumn = input$incidence_table_group_column,
        hide = input$incidence_table_hide,
        columnOrder = c(
          "cdm_name", "outcome_group", "outcome_cohort_name", "gestational_trimester", "maternal_age_group", "pregnancy_start_period",        
          "socioeconomic_status", "ethnicity", "nationallity", "birth_country", "variable_name", "variable_level", "estimate_name"                  
        ),
        factor = list(
          "outcome_group" = c("Adverse Events of Special Interest", "Maternal Adverse Events", "AESI Sensitivity (180 wash-out)"),
          "outcome_cohort_name" = outcomes,
          "maternal_age_group" = c("overall", "12 to 17", "18 to 34", "35 to 55"),
          "pregnancy_start_period" = c("overall", "Pre COVID-19", "COVID-19 main outbreak", "Post COVID-19 main outbreak"),
          "socioeconomic_status" = c("overall", paste0("Q", 1:5), "R", paste0("U", 1:5), "0N", "Missing"),
          "ethnicity" = c("overall", "White", "Black", "Asian", "Missing"),
          "nationallity" = c("overall", "Africa", "Asia", "Central/South America", "Europe", "North America", "Oceania", "Missing"),
          "birth_continent" = c("overall", "Africa", "Asia", "Central/South America", "Europe", "North America", "Oceania", "Missing"),
          "gestational_trimester" = c("overall", "Trimester 1", "Trimester 2", "Trimester 3", "Postpartum")
        )
      )
  })
  output$incidence_table <- gt::render_gt({
    getIncidenceTable()
  })
  output$incidence_table_download <- shiny::downloadHandler(
    filename = paste0("table_incidence.", input$incidence_table_format),
    content = function(file) {
      gt::gtsave(getIncidenceTable(), file)
    }
  )
  getIncidencePlot <- shiny::reactive({
    x <- getIncidenceData() |>
      omopgenerics::tidy()
    label <- c('cdm_name', 'outcome_cohort_name', 'gestational_trimester', 'maternal_age_group', 'pregnancy_start_period', 'socioeconomic_status', 'ethnicity', 'variable_name', 'variable_level', 'outcome_count', 'person_days_count', 'denominator_count', 'person_years', 'incidence_100000_pys', 'incidence_100000_pys_95CI_lower', 'incidence_100000_pys_95CI_upper')
    label <- label[label %in% colnames(x)]
    x |>
      dplyr::mutate(
        outcome_group = factor(
          .data$outcome_group, 
          levels = c("Adverse Events of Special Interest", "Maternal Adverse Events", "AESI Sensitivity (180 wash-out)")
        ),
        maternal_age_group = factor(
          maternal_age_group, levels = c("overall", "12 to 17", "18 to 34", "35 to 55")
        ),
        pregnancy_start_period = factor(
          pregnancy_start_period, levels = c("overall", "Pre COVID-19", "COVID-19 main outbreak", "Post COVID-19 main outbreak")
        ),
        socioeconomic_status = factor(
          socioeconomic_status, levels = c("overall", paste0("Q", 1:5), "R", paste0("U", 1:5), "0N", "Missing")
        ),
        ethnicity = factor(
          ethnicity, levels = c("overall", "White", "Black", "Asian", "Missing")
        ),
        nationallity = factor(
          nationallity, levels = c("overall", "Africa", "Asia", "Central/South America", "Europe", "North America", "Oceania", "Missing")
        ),
        birth_continent = factor(
          birth_continent, levels = c("overall", "Africa", "Asia", "Central/South America", "Europe", "North America", "Oceania", "Missing")
        ),
        gestational_trimester = factor(
          gestational_trimester, levels = c("overall", "Trimester 1", "Trimester 2", "Trimester 3", "Postpartum")
        )
      ) |>
      dplyr::filter(!is.na(.data$outcome_group)) |>
      dplyr::arrange() |>
      visOmopResults::scatterPlot(
        x = input$incidence_plot_x,
        y = "incidence_100000_pys",
        line = input$incidence_plot_line,
        point = TRUE,
        ribbon = input$incidence_plot_ribbon,
        ymin = "incidence_100000_pys_95CI_lower",
        ymax = "incidence_100000_pys_95CI_upper",
        facet = input$incidence_plot_facet,
        colour = input$incidence_plot_colour,
        style = "default",
        label = label
      ) + 
      ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust = 0.5, hjust=1)) +
      ggplot2::facet_wrap(input$incidence_plot_facet, scales = "free_y")
  })
  output$incidence_plot <- shiny::renderUI({
    x <- getIncidencePlot()
    renderInteractivePlot(x, input$incidence_plot_interactive)
  })
  output$incidence_plot_download <- shiny::downloadHandler(
    filename = "plot_incidence.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getIncidencePlot(),
        width = as.numeric(input$incidence_plot_width),
        height = as.numeric(input$incidence_plot_height),
        units = input$incidence_plot_units,
        dpi = as.numeric(input$incidence_plot_dpi)
      )
    }
  )
  getIncidencePlotPopulation <- shiny::reactive({
    getIncidenceData() |>
      IncidencePrevalence::plotIncidencePopulation(
        facet = input$incidence_plot_population_facet,
        colour = input$incidence_plot_population_colour
      )
  })
  output$incidence_plot_population <- shiny::renderUI({
    x <- getIncidencePlotPopulation()
    renderInteractivePlot(x, input$incidence_plot_population_interactive)
  })
  # cumulative incidence -----
  ## get survival_probability data
  getSurvivalData <- shiny::reactive({
    data[["survival"]]  |>
      omopgenerics::filterSettings(
        .data$outcome_group %in% input$survival_outcome_group
      ) |>
      dplyr::filter(
        .data$cdm_name %in% input$survival_cdm_name, 
        .data$variable_level %in% input$survival_outcome
      ) |>
      omopgenerics::filterStrata(
        .data$maternal_age_group %in% input$survival_maternal_age_group,
        .data$pregnancy_start_period %in% input$survival_pregnancy_start_period,
        .data$ethnicity %in% input$survival_ethnicity,
        .data$nationallity %in% input$survival_nationallity,
        .data$birth_continent %in% input$survival_birth_continent,
        .data$socioeconomic_status %in% input$survival_socioeconomic_status
      )
  })
  output$survival_outcome_cohort_name_picker <- shiny::renderUI({
    opts <- data[["survival"]]  |>
      omopgenerics::filterSettings(
        .data$outcome_group %in% input$survival_outcome_group
      ) |>
      dplyr::pull(variable_level) |>
      unique()
    shinyWidgets::pickerInput(
      inputId = "survival_outcome",
      label = "Outcome cohort name",
      choices = opts,
      selected = opts,
      multiple = TRUE,
      options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
    )
  })
  getSurvivalProbabilityTidy <- shiny::reactive({
    CohortSurvival::asSurvivalResult(getSurvivalData()) |>
      dplyr::select(!any_of(c("variable", "competing_outcome", "result_type", "target_cohort", "outcome_washout"))) 
  })
  output$survival_tidy <- DT::renderDT({
    getSurvivalProbabilityTidy()
  })
  output$survival_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSurvivalProbabilityData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSurvivalProbabilityTable <- shiny::reactive({
    header <- gsub("outcome_name", "variable_level", input$survival_table_header)
    groupColumn <- gsub("outcome_name", "variable_level", input$survival_table_groupColumn)
    hide <- gsub("outcome_name", "variable_level", input$survival_table_hide)
    
    table <- getSurvivalData()  |> 
      omopgenerics::filterSettings(grepl("probability", .data$result_type) | grepl("summary", .data$result_type)) |>
      dplyr::filter(estimate_name %in% c("n_events_count", "number_records_count")) 
    
    table <- dplyr::bind_rows(
      table, 
      table |>
        omopgenerics::pivotEstimates() |>
        dplyr::mutate(n_events_percentage = if_else(!is.na(n_events_count), as.character(n_events_count/number_records_count * 100), NA_character_)) |>
        dplyr::select(!c("n_events_count", "number_records_count")) |>
        dplyr::mutate(
          estimate_name = "n_events_percentage",
          estimate_type = "percentage"
        ) |>
        dplyr::rename("estimate_value" = "n_events_percentage")
    )
    
    if (length(input$survival_table_estimates) == 1) {
      if (input$survival_table_estimates == "Number pregnancies") {
        table <- table |> dplyr::filter(estimate_name == "number_records_count")
      } else {
        table <- table |> dplyr::filter(estimate_name != "number_records_count")
      }
    }
    
    outcomes <- table |>
      dplyr::filter(estimate_name == "n_events_percentage") |>
      dplyr::mutate(estimate_value = as.numeric(estimate_value)) |>
      dplyr::arrange(desc(estimate_value)) |>
      dplyr::pull(variable_level) |>
      unique()
    
    table |>
      mutate(
        estimate_name = factor(
          .data$estimate_name,
          levels = c(
            "number_records_count", "n_events_count", "n_events_percentage"
          ))
      ) %>%
      dplyr::arrange(.data$estimate_name) %>%
      dplyr::mutate("estimate_name" = as.character(.data$estimate_name)) |>
      dplyr::filter(!is.na(variable_name)) |>
      visOmopResults::visOmopTable(
        estimateName = c(
          "Number pregnancies" = "<number_records_count>",
          "Number outcomes" = "<n_events_count> (<n_events_percentage>%)"
        ),
        rename = c("Outcome name" = "variable_level"),
        header = input$survival_table_header,
        groupColumn = input$survival_table_groupColumn,
        hide = c("variable_name", input$survival_table_hide),
        settingsColumn = "outcome_group",
        columnOrder = c(
          "cdm_name", "target_cohort", "outcome_group", "variable_name", "variable_level",
          "maternal_age_group", "pregnancy_start_period", "socioeconomic_status",               
          "ethnicity", "nationallity", "birth_continent", "estimate_name"      
        ),
        factor = list(
          "outcome_group" = c("Adverse Events of Special Interest", "Maternal Adverse Events", "AESI Sensitivity (180 wash-out)"),
          "variable_level" = outcomes,
          "maternal_age_group" = c("overall", "12 to 17", "18 to 34", "35 to 55"),
          "pregnancy_start_period" = c("overall", "Pre COVID-19", "COVID-19 main outbreak", "Post COVID-19 main outbreak"),
          "socioeconomic_status" = c("overall", paste0("Q", 1:5), "R", paste0("U", 1:5), "0N", "Missing"),
          "ethnicity" = c("overall", "White", "Black", "Asian", "Missing"),
          "nationallity" = c("overall", "Africa", "Asia", "Central/South America", "Europe", "North America", "Oceania", "Missing"),
          "birth_continent" = c("overall", "Africa", "Asia", "Central/South America", "Europe", "North America", "Oceania", "Missing")
        )
      )
  })
  output$survival_table <- gt::render_gt({
    getSurvivalProbabilityTable()
  })
  output$survival_table_download <- shiny::downloadHandler(
    filename = "summarise_cohort_survival_gt.docx",
    content = function(file) {
      obj <- getSurvivalProbabilityTable()
      gt::gtsave(data = obj, filename = file)
    }
  )
  getSurvivalAtRiksTable <- shiny::reactive({
    header <- gsub("outcome_name", "variable_level", input$survival_at_risk_header)
    groupColumn <- gsub("outcome_name", "variable_level", input$survival_at_risk_groupColumn)
    CohortSurvival::riskTable(
      x = getSurvivalData(),
      header = header,
      groupColumn = groupColumn
    )
  })
  output$survival_at_risk_table <- gt::render_gt({
    getSurvivalAtRiksTable()
  })
  output$survival_at_risk_table_download <- shiny::downloadHandler(
    filename = "summarise_cohort_survival_at_risk_gt.docx",
    content = function(file) {
      obj <- getSurvivalAtRiksTable()
      gt::gtsave(data = obj, filename = file)
    }
  )
  createPlotSurvival <- shiny::reactive({
    result <- getSurvivalData()
    CohortSurvival::plotSurvival(
      result,
      timeScale = input$survival_time_scale,
      ribbon = input$survival_plot_ribbon,
      facet = input$survival_plot_facet,
      colour = input$survival_plot_colour,
      cumulativeFailure = input$survival_plot_cf
    ) +
      labs(color = "Color") +
      guides(fill = "none") +
      ggplot2::facet_wrap(input$survival_plot_facet, scales = "free_y")
  })
  output$summarise_cohort_survival_plot <- shiny::renderUI({
    if(isTRUE(input$survival_plot_interactive)){
      plot <- plotly::ggplotly(createPlotSurvival())
    } else {
      plot <- renderPlot(createPlotSurvival())
    }
    plot
  })
  output$summarise_cohort_survival_plot_download <- shiny::downloadHandler(
    filename = "summarise_cohort_survival_plot.png",
    content = function(file) {
      obj <- createPlotSurvival()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_cohort_survival_plot_download_width),
        height = as.numeric(input$summarise_cohort_survival_plot_download_height),
        units = input$summarise_cohort_survival_plot_download_units,
        dpi = as.numeric(input$summarise_cohort_survival_plot_download_dpi)
      )
    }
  )
}
