# Generated by OmopViewer 0.4.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "ohdsi_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    ""
  ),
  theme = bslib::bs_theme(bootswatch = "flatly"),
  bslib::nav_panel(
    title = "Abstract",
    icon = shiny::icon("book-atlas"),
    backgroundCard("background.md")
  ),
  # Snapshot ----
  bslib::nav_panel(
    title = "Data Snapshot",
    icon = shiny::icon("clipboard-list"),
    bslib::card_header(
      bslib::popover(
        shiny::icon("download"),
        shinyWidgets::pickerInput(
          inputId = "summarise_omop_snapshot_table_format",
          label = "Format",
          choices = c("docx", "png", "pdf", "html"),
          selected = "docx",
          multiple = FALSE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shiny::downloadButton(outputId = "summarise_omop_snapshot_table_download", label = "Download table")
      ),
      class = "text-end"
    ),
    gt::gt_output("summarise_omop_snapshot_table") |>
      shinycssloaders::withSpinner()
  ),
  # Cohort summary ----
  bslib::nav_menu(
    title = "Cohort summary",
    icon = shiny::icon("list"),
    ## Cohort count ----
    bslib::nav_panel(
      title = "Cohort Count",
      icon = shiny::icon("users"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_cdm_name",
            label = "CDM name",
            choices = choices$summarise_cohort_count_cdm_name,
            selected = selected$summarise_cohort_count_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_cohort_count_cohort_name,
            selected = selected$summarise_cohort_count_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_variable_name",
            label = "Variable name",
            choices = choices$summarise_cohort_count_variable_name,
            selected = selected$summarise_cohort_count_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_table_name",
            label = "Table name",
            choices = choices$summarise_cohort_count_table_name,
            selected = selected$summarise_cohort_count_table_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          width = 400, 
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Counts",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_count_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("variable_name", "estimate_name"),
                      input_id = "summarise_cohort_count_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "cohort_name",
                      input_id = "summarise_cohort_count_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = "cdm_name",
                      input_id = "summarise_cohort_count_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = c("variable_level", "table_name", "weighting"),
                      input_id = "summarise_cohort_count_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_cohort_count_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Counts",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_count_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_cohort_count_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name", "table_name", "weighting"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "cohort_name", "table_name", "weighting"),
                    selected = "cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_cohort_count_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    ## Cohort attrition ----
    bslib::nav_panel(
      title = "Cohort Attrition",
      icon = shiny::icon("layer-group"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_attrition_cdm_name",
            label = "CDM name",
            choices = choices$summarise_cohort_attrition_cdm_name,
            selected = selected$summarise_cohort_attrition_cdm_name[1],
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_attrition_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_cohort_attrition_cohort_name,
            selected = selected$summarise_cohort_attrition_cohort_name[1],
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_attrition_variable_name",
            label = "Variable name",
            choices = choices$summarise_cohort_attrition_variable_name,
            selected = selected$summarise_cohort_attrition_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          width = 400, 
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Attrition",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_attrition_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_attrition_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = "reason",
                      input_id = "summarise_cohort_attrition_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "variable_name",
                      input_id = "summarise_cohort_attrition_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_cohort_attrition_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = c("variable_level", "reason_id", "estimate_name", "cohort_definition_id", "sex", "table_name", "weighting"),
                      input_id = "summarise_cohort_attrition_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_cohort_attrition_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Diagram",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_attrition_diagram_width",
                    label = "Width (px)",
                    value = 2000
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_attrition_diagram_download", label = "Download Diagram")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_attrition_diagram_show",
                    label = "Show",
                    choices = c("subjects", "records"),
                    selected = c("subjects", "records"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                DiagrammeR::grVizOutput("summarise_cohort_attrition_diagram") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    ## Cohort code use -----
    bslib::nav_panel(
      title = "Cohort code use",
      icon = shiny::icon("chart-column"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          width = 400, 
          open = "closed",
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_cdm_name",
            label = "CDM name",
            choices = choices$cohort_code_use_cdm_name,
            selected = selected$cohort_code_use_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_cohort_name",
            label = "Cohort name",
            choices = choices$cohort_code_use_cohort_name,
            selected = selected$cohort_code_use_cohort_name[1],
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          bslib::accordion(
            bslib::accordion_panel(
              title = "Settings",
              shinyWidgets::pickerInput(
                inputId = "cohort_code_use_domain_id",
                label = "Domain",
                choices = choices$cohort_code_use_domain_id,
                selected = selected$cohort_code_use_domain_id,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              div(style="display: flex; justify-content: space-between;",
                  div(style="flex: 1;", prettyCheckbox(inputId = "cohort_code_use_person_count",
                                                       label = "Person count",
                                                       value = TRUE,
                                                       status = "primary",
                                                       shape = "curve",
                                                       outline = TRUE)),
                  div(style="flex: 1;", prettyCheckbox(inputId = "cohort_code_use_record_count",
                                                       label = "Record count",
                                                       value = TRUE,
                                                       status = "primary",
                                                       shape = "curve",
                                                       outline = TRUE))
              )
            ),
            bslib::accordion_panel(
              title = "Table formatting",
              materialSwitch(inputId = "cohort_code_use_interactive",
                             value = TRUE,
                             label = "Interactive",
                             status = "primary"),
              sortable::bucket_list(
                header = NULL,
                sortable::add_rank_list(
                  text = "none",
                  labels = c("cohort_name", "codelist_name", "source_concept_name", "source_concept_id", "domain_id", "variable_name", "variable_level"),
                  input_id = "cohort_code_use_gt_none"
                ),
                sortable::add_rank_list(
                  text = "header",
                  labels = c("cdm_name", "estimate_name"),
                  input_id = "cohort_code_use_gt_header"
                ),
                sortable::add_rank_list(
                  text = "groupColumn",
                  labels =  character(),
                  input_id = "cohort_code_use_gt_groupColumn"
                ),
                sortable::add_rank_list(
                  text = "hide",
                  labels = character(),
                  input_id = "cohort_code_use_gt_hide"
                )
              )
            )
          )
        ),
        bslib::nav_panel(
          title = "Table cohort code use",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              shiny::downloadButton(outputId = "cohort_code_use_download", label = ""),
              class = "text-end"
            ),
            uiOutput("cohort_code_use_tbl") |> withSpinner()
          )
        )
      )
    )
  ),
  # Background rates -----
  bslib::nav_menu(
    title = "Background rates",
    icon = shiny::icon("list"),
    ## Incidence ----
    bslib::nav_panel(
      title = "Incidence Rates",
      icon = shiny::icon("chart-line"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          width = 400, 
          open = "closed",
          shinyWidgets::pickerInput(
            inputId = "incidence_cdm_name",
            label = "CDM name",
            choices = choices$incidence_cdm_name,
            selected = selected$incidence_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_outcome_group",
            label = "Outcome cohort group",
            choices = c("Adverse Events of Special Interest", "Maternal Adverse Events", "AESI Sensitivity (180 wash-out)"),
            selected = c("Adverse Events of Special Interest", "Maternal Adverse Events"),
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          uiOutput("incidence_outcome_cohort_name_picker"),
          shinyWidgets::pickerInput(
            inputId = "incidence_gestational_trimester",
            label = "Gestational trimester",
            choices = choices$incidence_gestational_trimester,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_maternal_age_group",
            label = "Maternal age",
            choices = choices$incidence_maternal_age_group,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_pregnancy_start_period",
            label = "Pregnancy start period",
            choices = choices$incidence_pregnancy_start_period,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_socioeconomic_status",
            label = "Socioeconomic status",
            choices = choices$incidence_socioeconomic_status,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_ethnicity",
            label = "Ethnicity",
            choices = choices$incidence_ethnicity,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_nationallity",
            label = "Nationallity",
            choices = choices$incidence_nationallity,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_birth_continent",
            label = "Birth continent",
            choices = choices$incidence_birth_continent,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_estimate_name",
            label = "Estimate name",
            choices = choices$incidence_estimate_name,
            selected = c(
              "denominator_count", "incidence_100000_pys", "incidence_100000_pys_95CI_lower", "incidence_100000_pys_95CI_upper",
              "outcome_count", "outcome_in_period_count", "outcome_in_period_percentage", "person_days_count"        
            ),
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "incidence_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "incidence_tidy_columns",
                    label = "Columns",
                    choices = c('cdm_name', 'outcome_cohort_name', 'gestational_trimester', 'maternal_age_group', 'pregnancy_start_period', 'socioeconomic_status', 'ethnicity', 'birth_continent', 'nationallity', 'variable_name', 'variable_level', 'outcome_count', 'person_days_count', 'denominator_count', 'person_years', 'incidence_100000_pys', 'incidence_100000_pys_95CI_lower', 'incidence_100000_pys_95CI_upper', 'outcome_in_period_count', 'outcome_in_period_percentage'),
                    selected = c('cdm_name', 'outcome_cohort_name', 'outcome_count', 'person_days_count', 'denominator_count', 'person_years', 'incidence_100000_pys', 'incidence_100000_pys_95CI_lower', 'incidence_100000_pys_95CI_upper', 'outcome_in_period_count', 'outcome_in_period_percentage'),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::checkboxInput(
                    inputId = "incidence_tidy_pivot_estimates",
                    label = "Pivot estimates",
                    value = TRUE
                  ),
                  position = "right"
                ),
                reactable::reactableOutput("incidence_tidy") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Table Incidence",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "incidence_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c('outcome_group', "outcome_cohort_name"),
                      input_id = "incidence_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "estimate_name",
                      input_id = "incidence_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = c("cdm_name"),
                      input_id = "incidence_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = c('gestational_trimester', 'maternal_age_group', 'pregnancy_start_period', 'socioeconomic_status', 'ethnicity', 'birth_continent', 'nationallity', 'variable_name', 'variable_level'),
                      input_id = "incidence_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("incidence_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Incidence",
            bslib::card(
              height = "90vh",
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "incidence_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "incidence_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "incidence_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "incidence_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                height = "90vh",
                full_screen = TRUE,
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "incidence_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_plot_x",
                    label = "X axis",
                    choices = c("cdm_name", "outcome_cohort_name", "gestational_trimester", 'maternal_age_group', 'pregnancy_start_period', 'socioeconomic_status', 'ethnicity', 'birth_continent', 'nationallity'),
                    selected = "outcome_cohort_name",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "outcome_group", "outcome_cohort_name", "gestational_trimester", 'maternal_age_group', 'pregnancy_start_period', 'socioeconomic_status', 'ethnicity', 'birth_continent', 'nationallity'),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "outcome_group", "outcome_cohort_name", "gestational_trimester", 'maternal_age_group', 'pregnancy_start_period', 'socioeconomic_status', 'ethnicity', 'birth_continent', 'nationallity'),
                    selected = "outcome_group",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::materialSwitch(
                    inputId = "incidence_plot_ribbon",
                    label = "Ribbon",
                    value = FALSE
                  ),
                  shinyWidgets::materialSwitch(
                    inputId = "incidence_plot_line",
                    label = "Line",
                    value = FALSE
                  ),
                  position = "right"
                ),
                shiny::uiOutput("incidence_plot", height = "100%") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    ## Cumulative Incidence -----
    bslib::nav_panel(
      title = "Cumulative Incidence",
      icon = shiny::icon("chart-gantt"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          width = 400, 
          open = "closed",
          shinyWidgets::pickerInput(
            inputId = "survival_cdm_name",
            label = "CDM name",
            choices = choices$survival_cdm_name,
            selected = selected$survival_cdm_name[1],
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "survival_outcome_group",
            label = "Outcome group name",
            choices = choices$survival_outcome_group,
            selected = selected$survival_outcome_group[1],
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          uiOutput("survival_outcome_cohort_name_picker"),
          shinyWidgets::pickerInput(
            inputId = "survival_maternal_age_group",
            label = "Maternal age",
            choices = choices$survival_maternal_age_group,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "survival_pregnancy_start_period",
            label = "Pregnancy start period",
            choices = choices$survival_pregnancy_start_period,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "survival_socioeconomic_status",
            label = "Socioecnomic status",
            choices = choices$survival_socioeconomic_status,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "survival_ethnicity",
            label = "Ethhnicity",
            choices = choices$survival_ethnicity,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "survival_nationallity",
            label = "Nationallity",
            choices = choices$survival_nationallity,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "survival_birth_continent",
            label = "Birth continent",
            choices = choices$survival_birth_continent,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "survival_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              DT::DTOutput("survival_tidy") |>
                shinycssloaders::withSpinner()
            )
          ),
          bslib::nav_panel(
            title = "Table",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "survival_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "survival_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "survival_table_estimates",
                    label = "Estimates",
                    choices = c("Number pregnancies", "Number outcomes"),
                    selected = c("Number pregnancies", "Number outcomes"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  sortable::bucket_list(
                    header = "Table formatting",
                    sortable::add_rank_list(
                      text = "none",
                      labels = c("outcome_name"),
                      input_id = "survival_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "header",
                      labels = c("cdm_name", "estimate_name"),
                      input_id = "survival_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "groupColumn",
                      labels = c(),
                      input_id = "survival_table_groupColumn"
                    ),
                    sortable::add_rank_list(
                      text = "hide",
                      labels = c("maternal_age_group", "pregnancy_start_period", "socioeconomic_status", "ethnicity", 'birth_continent', 'nationallity', "target_cohort", "time"),
                      input_id = "survival_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("survival_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_survival_plot_download_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_survival_plot_download_height",
                    label = "Height",
                    value = 10
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_survival_plot_download_units",
                    label = "Units",
                    selected = "cm",
                    choices = c("px", "cm", "inch"),
                    multiple = FALSE
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_survival_plot_download_dpi",
                    label = "dpi",
                    value = 300
                  ),
                  shiny::downloadButton(
                    outputId = "summarise_cohort_survival_plot_download", 
                    label = "Download"
                  )
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  width = 400, open = "closed",
                  materialSwitch(
                    inputId = "survival_plot_interactive",
                    value = TRUE,
                    label = "Interactive",
                    status = "primary"
                  ),
                  shiny::checkboxInput(
                    inputId = "survival_plot_ribbon",
                    label = "Ribbon",
                    value = c(TRUE)
                  ),
                  shiny::checkboxInput(
                    inputId = "survival_plot_cf",
                    label = "Plot cumulative failure",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "survival_plot_colour",
                    label = "Colour",
                    selected = c("outcome"),
                    multiple = TRUE,
                    choices = c("cdm_name", "outcome", "maternal_age_group", "pregnancy_start_period", "socioeconomic_status", "ethnicity", 'birth_continent', 'nationallity'),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "survival_plot_facet",
                    label = "Facet",
                    selected = c("cdm_name"),
                    multiple = TRUE,
                    choices = c("cdm_name", "outcome", "maternal_age_group", "pregnancy_start_period", "socioeconomic_status", "ethnicity", 'birth_continent', 'nationallity'),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "survival_time_scale",
                    label = "Time scale",
                    choices = c("days", "months", "years"),
                    selected = "days",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                uiOutput("summarise_cohort_survival_plot") |> 
                  withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  # Characterisation ----
  bslib::nav_menu(
    title = "Characterisation",
    icon = shiny::icon("list"),
    ## Characterisation ----
    bslib::nav_panel(
      title = "Cohort Characteristics",
      icon = shiny::icon("users-gear"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_cdm_name",
            label = "CDM name",
            choices = choices$summarise_characteristics_cdm_name,
            selected = selected$summarise_characteristics_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_cohort_name",
            label = "Cohort name",
            choices = unique(gsub("_matched|_sampled", "", choices$summarise_characteristics_cohort_name)),
            selected = unique(gsub("_matched|_sampled", "", selected$summarise_characteristics_cohort_name[1])),
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_cohort_name_type",
            label = "Cohort type",
            choices = c("original", "matched", "sampled"),
            selected = "original",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_maternal_age_group",
            label = "Maternal age",
            choices = choices$summarise_characteristics_maternal_age_group,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_trimester",
            label = "Trimester",
            choices = choices$summarise_characteristics_trimester,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_pregnancy_start_period",
            label = "Pregnancy start period",
            choices = choices$summarise_characteristics_pregnancy_start_period,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_socioeconomic_status",
            label = "Socioeconomic status",
            choices = choices$summarise_characteristics_socioeconomic_status,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_ethnicity",
            label = "Ethnicity",
            choices = choices$summarise_characteristics_ethnicity,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_nationallity",
            label = "Nationallity",
            choices = choices$summarise_characteristics_nationallity,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_birth_continent",
            label = "Birth continent",
            choices = choices$summarise_characteristics_birth_continent,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_variable_name",
            label = "Variable name",
            choices = c(
              "Number records", "Number subjects", "Maternal age", "Maternal age group",
              "Trimester", "Season", "Previous pregnancies",
              "Ethnicity", "Birth continent", "Nationallity", 
              'Socioeconomic status',
              "Mental heatlh problems in the last year",
              "Covariates in the past 5 years",
              "History of comorbidities", "Medications in the past year"
            ),
            selected = c(
              "Number records", "Number subjects", "Maternal age", "Maternal age group",
              "Trimester", "Season", "Previous pregnancies",
              "Ethnicity", "Birth continent", "Nationallity", 
              'Socioeconomic status',
              "Mental heatlh problems in the last year",
              "Covariates in the past 5 years",
              "History of comorbidities", "Medications in the past year"
            ),
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_characteristics_estimate_name,
            selected = selected$summarise_characteristics_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          width = 400, 
          open = "closed",
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_characteristics_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_characteristics_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = character(),
                      input_id = "summarise_characteristics_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = c("table_name", 'trimester', 'maternal_age_group', 'pregnancy_start_period', 'socioeconomic_status', 'ethnicity', 'birth_continent', 'nationallity'),
                      input_id = "summarise_characteristics_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_characteristics_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_characteristics_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_plot_type",
                    label = "Plot type",
                    choices = c("boxplot", "barplot", "scatterplot"),
                    selected = "boxplot",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "cohort_name"),
                    selected = "cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_characteristics_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    ## Large Scale Characteristics ----
    bslib::nav_panel(
      title = "Large Scale Characteristics",
      icon = shiny::icon("arrow-up-right-dots"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_cdm_name",
            label = "CDM name",
            choices = choices$summarise_large_scale_characteristics_cdm_name,
            selected = selected$summarise_large_scale_characteristics_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_cohort_name",
            label = "Cohort name",
            choices = unique(gsub("_matched|_sampled", "", choices$summarise_characteristics_cohort_name)),
            selected = unique(gsub("_matched|_sampled", "", selected$summarise_characteristics_cohort_name))[1],
            multiple = FALSE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_cohort_name_type",
            label = "Cohort type",
            choices = c("original", "matched", "sampled"),
            selected = "original",
            multiple = FALSE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_maternal_age_group",
            label = "Maternal age",
            choices = choices$summarise_large_scale_characteristics_maternal_age_group,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_trimester",
            label = "Trimester",
            choices = choices$summarise_large_scale_characteristics_trimester,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_pregnancy_start_period",
            label = "Pregnancy start period",
            choices = choices$summarise_large_scale_characteristics_pregnancy_start_period,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_socioeconomic_status",
            label = "Socioeconomic status",
            choices = choices$summarise_large_scale_characteristics_socioeconomic_status,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_ethnicity",
            label = "Ethnicity",
            choices = choices$summarise_large_scale_characteristics_ethnicity,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_nationallity",
            label = "Nationallity",
            choices = choices$summarise_large_scale_characteristics_nationallity,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_birth_continent",
            label = "Birth continent",
            choices = choices$summarise_large_scale_characteristics_birth_continent,
            selected = "overall",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_variable_level",
            label = "Time window",
            choices = choices$summarise_large_scale_characteristics_variable_level,
            selected = selected$summarise_large_scale_characteristics_variable_level,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_table_name",
            label = "Table name",
            choices = choices$summarise_large_scale_characteristics_table_name,
            selected = selected$summarise_large_scale_characteristics_table_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_type",
            label = "Type",
            choices = choices$summarise_large_scale_characteristics_type,
            selected = selected$summarise_large_scale_characteristics_type,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          width = 400, 
          open = "closed",
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_large_scale_characteristics_table_lsc_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_table_lsc_hide",
                    label = "Hide",
                    choices = c("cdm_name", "type", "variable_name", "variable_level", 'trimester', 'maternal_age_group', 'pregnancy_start_period', 'socioeconomic_status', 'ethnicity', 'birth_continent', 'nationallity'),
                    selected = c('trimester', 'maternal_age_group', 'pregnancy_start_period', 'socioeconomic_status', 'ethnicity', 'ethnicity', 'birth_continent', 'nationallity', "type"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                reactable::reactableOutput("summarise_large_scale_characteristics_table_lsc") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Table Compared",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_large_scale_characteristics_table_lsc_compared_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_compared_cohort_name",
                    label = "Comparator cohort name",
                    choices = unique(gsub("_matched|_sampled", "", choices$summarise_characteristics_cohort_name)),
                    selected = unique(gsub("_matched|_sampled", "", selected$summarise_characteristics_cohort_name))[1],
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_compared_cohort_name_type",
                    label = "Comparator chort type",
                    choices = c("original", "matched", "sampled"),
                    selected = "matched",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_table_lsc_compared_hide",
                    label = "Hide",
                    choices = c("cdm_name", "type", "variable_name", "variable_level", "smd", "asmd", 'trimester', 'maternal_age_group', 'pregnancy_start_period', 'socioeconomic_status', 'ethnicity', 'birth_continent', 'nationallity'),
                    selected = c('trimester', 'maternal_age_group', 'pregnancy_start_period', 'socioeconomic_status', 'ethnicity', 'birth_continent', 'nationallity', "type"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                reactable::reactableOutput("summarise_large_scale_characteristics_table_lsc_compared") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Compared",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_large_scale_characteristics_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_large_scale_characteristics_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_large_scale_characteristics_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_large_scale_characteristics_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_large_scale_characteristics_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::materialSwitch(
                    inputId = "legend_none",
                    label = "Show legend",
                    value = FALSE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_compared_cohort_name",
                    label = "Comparator cohort name",
                    choices = unique(gsub("_matched|_sampled", "", choices$summarise_characteristics_cohort_name)),
                    selected = unique(gsub("_matched|_sampled", "", selected$summarise_characteristics_cohort_name))[1],
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_compared_cohort_name_type",
                    label = "Comparator chort type",
                    choices = c("original", "matched", "sampled"),
                    selected = "matched",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_plot_compared_colour",
                    label = "Colour",
                    choices = c("cdm_name", "cohort_name", 'trimester', 'maternal_age_group', 'pregnancy_start_period', 'socioeconomic_status', 'ethnicity', 'birth_continent', 'nationallity', "type", "concept_id", "concept_name"),
                    selected = "concept_name",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_plot_compared_facet",
                    label = "Facet",
                    choices = c("cdm_name", 'trimester', 'maternal_age_group', 'pregnancy_start_period', 'socioeconomic_status', 'ethnicity', 'birth_continent', 'nationallity', "type", "concept_id", "concept_name"),
                    selected = c("cdm_name"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_large_scale_characteristics_plot_compared") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.4.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
